### ISSUE TITLE
Problems accessing the stick

### ISSUE THREAD

**Issue by hapklaar** [cyberjunky/home-assistant-plugwise#2]
First of all thanks for making this. Love to get my Plugwise circles intergrated in HA and never have to use the Stretch anymore :)

I installed everything following your guide, but am unsure on how to proceed to get the circles to switch or measured in HA. Should the Plugwise circles be present as entities in HA after install and server restart? I don't see any yet.

This could be due to the fact that initialization of the Stick seems to go wrong, in home-assistant.log I get the following error after restart:

```
homeassistant@HapPi4:~/.homeassistant $ cat home-assistant.log
2020-03-03 18:19:56 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-03 18:20:02 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plugwise which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-03 18:20:13 WARNING (MainThread) [homeassistant.components.switch] Setup of switch platform plugwise is taking over 10 seconds.
2020-03-03 18:20:14 ERROR (MainThread) [homeassistant.components.switch] plugwise: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity_platform.py", line 312, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.7/site-packages/homeassistant/helpers/entity.py", line 476, in async_device_update
    await self.hass.async_add_executor_job(self.update)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/homeassistant/.homeassistant/custom_components/plugwise/switch.py", line 104, in update
    self.data.update()
  File "/home/homeassistant/.homeassistant/custom_components/plugwise/switch.py", line 124, in update
    self.current_consumption = plugwise.Circle(self.mac, self.stick).get_power_usage()
  File "/srv/homeassistant/lib/python3.7/site-packages/plugwise/api.py", line 176, in get_power_usage
    pulse_1s, _, _ = self.get_pulse_counters()
  File "/srv/homeassistant/lib/python3.7/site-packages/plugwise/api.py", line 159, in get_pulse_counters
    resp = self._expect_response(PlugwisePowerUsageResponse)
  File "/srv/homeassistant/lib/python3.7/site-packages/plugwise/api.py", line 114, in _expect_response
    return self._comchan.expect_response(response_class, self.mac)
  File "/srv/homeassistant/lib/python3.7/site-packages/plugwise/api.py", line 73, in expect_response
    retval = self._recv_response(resp)
  File "/srv/homeassistant/lib/python3.7/site-packages/plugwise/api.py", line 53, in _recv_response
    raise TimeoutException("Timeout while waiting for response from device")
plugwise.exceptions.TimeoutException: Timeout while waiting for response from device

```

I have the following defined in configuration.yaml:
```
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

switch:
 - platform: plugwise
    port: /dev/ttyUSB0
   circles:
     CirclePlus: 000D6F0000588DB0
     Plug_76990D: 000D6F000076990D

```

In dmesg log I see the Stick being detected and it also works with Source app on Windows:

```
[187589.369525] usb 1-1.1: new full-speed USB device number 10 using xhci_hcd
[187589.515657] usb 1-1.1: New USB device found, idVendor=0403, idProduct=6001, bcdDevice= 6.00
[187589.515674] usb 1-1.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[187589.515688] usb 1-1.1: Product: FT232R USB UART
[187589.515700] usb 1-1.1: Manufacturer: FTDI
[187589.515712] usb 1-1.1: SerialNumber: A5013Y63
[187589.522371] ftdi_sio 1-1.1:1.0: FTDI USB Serial Device converter detected
[187589.522536] usb 1-1.1: Detected FT232RL
[187589.525647] usb 1-1.1: FTDI USB Serial Device converter now attached to ttyUSB0

```

What could be wrong?

**Comment by hapklaar** [comment]
Did some more digging in the logs provided by HA and found the communication actually seems to work and circles are being read. The error was specific to the CirclePlus not being found.

```
homeassistant@HapPi4:~/.homeassistant $ tail -f home-assistant.log | grep plugwise

tail: home-assistant.log: file truncated
2020-03-03 19:37:33 WARNING (MainThread) [homeassistant.loader] You are using a custom integration for plugwise which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you do experience issues with Home Assistant.
2020-03-03 19:37:33 INFO (MainThread) [homeassistant.components.switch] Setting up switch.plugwise
2020-03-03 19:37:33 INFO (SyncWorker_1) [custom_components.plugwise.switch] Connected to Plugwise stick
2020-03-03 19:37:33 INFO (SyncWorker_1) [custom_components.plugwise.switch] Created Plugwise switch for Circle: Plug_76990D
2020-03-03 19:37:33 INFO (SyncWorker_1) [custom_components.plugwise.switch] Created Plugwise switch for Circle: Aquarium
2020-03-03 19:37:33 DEBUG (SyncWorker_9) [custom_components.plugwise.switch] Current Consumption: 0.0
2020-03-03 19:37:34 DEBUG (SyncWorker_9) [custom_components.plugwise.switch] Relay State: 1
2020-03-03 19:37:34 DEBUG (SyncWorker_16) [custom_components.plugwise.switch] Current Consumption: 87.4121800407747
2020-03-03 19:37:34 DEBUG (SyncWorker_16) [custom_components.plugwise.switch] Relay State: 1
2020-03-03 19:38:05 DEBUG (SyncWorker_11) [custom_components.plugwise.switch] Current Consumption: 0.0
2020-03-03 19:38:05 DEBUG (SyncWorker_11) [custom_components.plugwise.switch] Relay State: 1
2020-03-03 19:38:05 DEBUG (SyncWorker_3) [custom_components.plugwise.switch] Current Consumption: 89.54171809832103
2020-03-03 19:38:05 DEBUG (SyncWorker_3) [custom_components.plugwise.switch] Relay State: 1
2020-03-03 19:38:36 DEBUG (SyncWorker_6) [custom_components.plugwise.switch] Current Consumption: 87.4121800407747
2020-03-03 19:38:36 DEBUG (SyncWorker_6) [custom_components.plugwise.switch] Relay State: 1
2020-03-03 19:38:36 DEBUG (SyncWorker_3) [custom_components.plugwise.switch] Current Consumption: 0.0
2020-03-03 19:38:36 DEBUG (SyncWorker_3) [custom_components.plugwise.switch] Relay State: 1

```

But how can I now use them in HA? :)

**Comment by cyberjunky** [comment]
You should see two switches in HA.
You can create two power sensors for them like so:
Not sure if you need to use all lowercase for device names.

```
# Example sensor.yaml entry

- platform: template
  sensors:
    Plug_76990D_power_usage:
      friendly_name: "Plug_76990DPower Usage"
      unit_of_measurement: 'Watt'
      value_template: "{{ states.switch.Plug_76990D.attributes.current_consumption }}"

    Aquarium_power_usage:
      friendly_name: "Aquarium Power Usage"
      unit_of_measurement: 'Watt'
      value_template: "{{ states.switch.Aquarium.attributes.current_consumption }}"
```

**Comment by hapklaar** [comment]
Ok describing everything in here gave some new insights. The devices were present, but browser cache thought otherwise. After clearing the cache I can see them in the entities list.

**Comment by hapklaar** [comment]
You were right, device names had to be in lowercase. All seems fine now. Thanks!
